# Generated by Django 5.0.4 on 2024-04-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genshin_code_notifier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='provider',
            field=models.CharField(default='default', max_length=20),
            preserve_default=False,
        ),
    ]
