# Generated by Django 5.0.4 on 2024-04-12 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genshin_code_notifier', '0003_rename_provider_user_carrier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
