# Generated by Django 5.0.4 on 2024-04-12 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genshin_code_notifier', '0004_alter_code_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='code',
            old_name='code',
            new_name='link',
        ),
    ]
