# Generated by Django 5.0.4 on 2024-04-12 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genshin_code_notifier', '0005_rename_code_code_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
